steps:
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo ">> Aplicando DDL..."
        bq query --use_legacy_sql=false --project_id=${REPO_NAME} < sql/ddl/tablas_riesgos.sql

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        ROWS=$(bq query --use_legacy_sql=false --project_id=${REPO_NAME} --format=csv "SELECT COUNT(*) FROM \`riesgos.transacciones\`" | tail -n 1)
        if [ "$$ROWS" -eq "0" ]; then
          echo ">> Cargando datos de muestra..."
          bq query --use_legacy_sql=false --project_id=${REPO_NAME} < sql/seed/load_sample_data.sql
        else
          echo ">> Saltando seed (ya hay $$ROWS filas)"
        fi

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo ">> Reporte AML (Caso 1)..."
        bq query --use_legacy_sql=false --project_id=${REPO_NAME} --max_rows=100 < sql/reports/caso_1_aml.sql

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo ">> Reporte Smurfing (Caso 2)..."
        bq query --use_legacy_sql=false --project_id=${REPO_NAME} --max_rows=100 < sql/reports/caso_2_smurfing.sql

options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET